-- ReplicatedStorage.MeleeWeaponData
return {
	-- Format: [developmentName] = {properties}
	["Knife_Default"] = {
		displayName = "Pocket Knife",
		rarity = "Common", -- Common, Uncommon, Rare, Epic, Legendary, etc.
		price = 0,
		description = "low range, low damage. a true classic"
	},
	["Machete_Default"] = {
		displayName = "Machete",
		rarity = "Uncommon",
		price = 150,
		description = "just like your favorite horror movies"
	},
	["Katana_Default"] = {
		displayName = "Katana",
		rarity = "Rare",
		price = "500",
		description = "great range and damage. not to mention it looks great"
	}
	-- Add more weapons...
}