-- ReplicatedStorage.WeaponData
return {
	-- Format: [developmentName] = {properties}
	["Blaster_Default"] = {
		displayName = "Pew Pew Blaster",
		rarity = "Common", -- Common, Uncommon, Rare, Epic, Legendary, etc.
		price = 0,
		description = "standard issue prop eliminator. nothing crazy, but it gets the job done."
	},
	["Hunter_Default"] = {
		displayName = "Hand Cannon",
		rarity = "Rare",
		price = 150,
		description = "packs a punch that'll send props flying"
	},
	-- Add more weapons...
}